[package]
name = "cliprd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.58"
async-std = "1.12.0"
cocoa = { version = "0.24.0" }
objc = "0.2.3"
rustyline = "9.1.0"
serde = { version = "1.0.139", features = ["derive"] }
thiserror = "1.0.31"
toml = "0.5.9"
# fasthash = "0.4"

[[bin]]
name = "cliprd"

[[bin]]
name = "clipr"
