[package]
name = "clipr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
cocoa = { version = "0.24.0" }
objc = "0.2.3"
rustyline = "9.1.0"
# fasthash = "0.4"