host = "127.0.0.1"
port = 1515
interactive = true
db = "./db.json"
lifetime = "1w"
min_entries = 512

[rewrites]
mattermost = { regex = '^https://(?<url>mm\.company\.net/.*$)', rewrite = 'mattermost://$url' }
