[package]
name = "clipr-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
async-std = { workspace = true }
surf = { workspace = true }
clipr-common = { path = "../clipr-common" }
