[package]
name = "clipr-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clipr-common = { path = "../clipr-common" }
async-std = { version = "1.12.0", features = ["attributes"] }
anyhow = "1.0.58"
clap = { version = "3.2.14", features = ["derive"] }
surf = "2.3.2"
