[package]
name = "clipr-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
async-std = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }